### PR TITLE
Don't try to equip a moveable feast between each adventure when...

### PR DESCRIPTION
**Pull request by tyrion-the-imp**
there is no access to one.

### CODE REVIEW

**Review by Rinn — CHANGES_REQUESTED** [review]
this will prevent a user that owns a moveable feast that has a stashClan set to none from using it, you would also need to check if one is available

**Comment by tyrion-the-imp** [comment]
OK...think it's right now?

**Comment by horrible-little-slime** [comment]
Feels like a more elegant fix would just be to track whether we've tried to moveable feast with a pref or a variable

**Comment by tyrion-the-imp** [comment]
> Feels like a more elegant fix would just be to track whether we've tried to moveable feast with a pref or a variable

I wasn't even sure how the feast worked.  I just wanted to stop my character pane from flashing red between each yachtzee turn. (This does fix that.)

**Pull request closed without merging**
