### PR TITLE
Add a warning if today is halloween

### PR DESCRIPTION
**Pull request by pstalcup**

### CODE REVIEW

**Comment by gausie** [comment]
I'm dumb and need something like this for sure

**Comment by horrible-little-slime** [comment]
Per discussion in discord, please add a userpref for disabling this. I don't think that qualifies as scope creep, given that it falls under the fairly rigid guideline of "things that make garbo terminate unceremoniously that are ultimately not that dangerous to just let it run for"

**Comment by pstalcup** [comment]
I am goign to leave this PR open, but I would like to revisit it from a different perspective (since we do have time before halloween comes.) I created a new issue #716 where we can have some design discussion before committing to ideas.

**Comment by horrible-little-slime** [comment]
Next halloween is 24 March 2022

**Comment by horrible-little-slime** [comment]
:broom:

**Comment by horrible-little-slime** [comment]
I'm closing this because of ctrlv and talks of the `ween` flag

**Pull request closed without merging**
