### PR TITLE
Move to esbuild for extremely fast building

### PR DESCRIPTION
**Pull request by gausie**
Still need to add watch building and then actually test it.

### CODE REVIEW

**Comment by horrible-little-slime** [comment]
I'm still interested in this if you are. Or if you aren't.

**Comment by phulin** [comment]
oh you requested a review from me and i never responded, whoops. fast build would be cool

**Comment by phulin** [comment]
@gausie I think this is good to go at this point? That phantom error has disappeared. Maybe it was fixed in a newer version of esbuild.

**Comment by horrible-little-slime** [comment]
@gausie if you resolve merge conflicts and verify it builds, I'd love to merge this

**Comment by Rinn** [comment]
Okay I got the conflicts resolved and fixed an issue with building the relay script and I'm testing a build now.

**Comment by Rinn** [comment]
seems to be good, got through yachtzeechain and embezzlers fine

**Review by lewismd13 — APPROVED** [review]

**Pull request merged**
