### PR TITLE
Avoid ML when fighting glitch monster

### PR DESCRIPTION
**Pull request by Shiverwarp**

### CODE REVIEW

**Comment by horrible-little-slime** [comment]
Is this tested?

**Comment by Shiverwarp** [comment]
> Is this tested?

Not yet, I'll be testing Revers build today.

I can probably test it tomorrow if needed, though I don't have the equipment that causes problems. If nasurte is around I can ask them to test it.

What would be "incorrect" behavior here? Is the reason we're maximizing mainstat just to try to better support people who don't have all the skills needed to kill safely without being hit?

If it equips HOA or Space Trip, is that undesireable?

**Comment by horrible-little-slime** [comment]
Mostly we're looking for:
 - It accomplishes its goal
 - It doesn't set anything on fire from the consequences of the code
 - It doesn't set anything on fire from the consequences of the decisions in the code

**Comment by Shiverwarp** [comment]
Tested now, works fine (avoids equipping my skeleton lord shield)

**Pull request merged**
