### PR TITLE
Check for turtle tamer adventures while mapping monsters

### PR DESCRIPTION
**Pull request by s-k-z**

### CODE REVIEW

**Comment by horrible-little-slime** [comment]
I sometimes run into a similar issue while checking WLF? Is there a way to generalize this solution?

**Comment by s-k-z** [comment]
You can get turtle adventures at the WLF bunker?

**Comment by s-k-z** [comment]
I think we can make checking for turtle adventures more general, but it needs to be applied in any place where we do visitUrl with an adv.php location and for gingerbread city it seems to be necessary for the counters there which uses adv1.

**Comment by horrible-little-slime** [comment]
Either that or wherever we go right before then.

**Pull request merged**
