### PR TITLE
ITEMS.md January update

### PR DESCRIPTION
**Pull request by s-k-z**
Add Cookbookbat recipes with mention that you do not need to own the Cookbookbat to benefit.
Add trainset and autumn-aton.
Add drinking to drink and hollow leg.

### CODE REVIEW

**Comment by docrostov** [comment]
thank you for this. do you mind if i do a small PR on your PR to fix some other lil stuff with items.md i wanted to fix?

**Comment by s-k-z** [comment]
Sure, that'd be great.

**Comment by docrostov** [comment]
> Sure, that'd be great.

FYI, PR'd your PR; once you've merged it i can review/merge this into main

**Comment by s-k-z** [comment]
Oh! I didn't notice it since there was no reference here. Thanks for letting me know.

**Pull request merged**
